name: Docker CI/CD script

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./docker/Dockerfile
          tags: ipocs92/api-server-${{ github.ref_name }}:latest
      -
        name: run docker-componse by ssh connection
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          command: |
            cd /home/sdcodebase/pocs-blog
            ls -apls
            pwd
            ./deploy.sh